#!/usr/bin/env bash
# Bootstrap the CI environment.
#
# Copyright (c) 2016-2018 Cisco and/or its affiliates.
# License: MIT


set -e
cd "$(dirname "$0")/.."


# Initialize the CI environment
echo "==> Bootstrapping the CI environment"


echo "Installing pipenv"
pip install --upgrade pipenv
