#!/usr/bin/env bash
# Run the project's test suite(s).
#
# Copyright (c) 2016-2020 Cisco and/or its affiliates.
# License: MIT


# Run all tests by default
default=true


# Process Script Arguments
for i in "${@}"; do
    case ${i} in
        lint)
        lint=true
        default=
        ;;

        tests)
        tests=true
        default=
        ;;

        slow)
        slow=true
        default=
        ;;

        manual)
        slow=true
        default=
        ;;

        *)
        echo "Unknown argument: $i"
        exit 1
        ;;
    esac
done


set -e
cd "$(dirname "$0")/.."


# Lint the source code
if [ ${default} ] || [ ${lint} ]; then
    echo "==> Linting the source code"
    flake8
fi

# Run the test suite
if [ ${default} ] || [ ${tests} ]; then
    echo "==> Running the test suite (excluding slow and manual tests)"
    py.test -s -m "not slow not manual"
fi

# Run the slow tests
if [ ${slow} ]; then
    echo "==> Running the slow tests"
    py.test -s -m "slow"
fi

# Run the slow tests
if [ ${manual} ]; then
    echo "==> Running the manual tests"
    py.test -s -m "manual"
fi
