#!/usr/bin/env bash
# Update the project's dependencies.
#
# Copyright (c) 2016-2018 Cisco and/or its affiliates.
# License: MIT


set -e
cd "$(dirname "$0")/.."


echo "==> Updating project dependencies"

echo "Update installed packages"
pipenv update --dev

echo "Freeze package requirements"
pipenv run pip freeze > requirements.lock

echo "Update versioneer script(s)"
rm versioneer.py
pipenv run versioneer install
echo "Done."
