on:
  push:
    tags:
      - "v*.*"
      - "v*.*.*"

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment: test.pypi.org
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Get Webex Token
        run: |
          echo "WEBEX_TEAMS_ACCESS_TOKEN=$(curl -s ${{ vars.WEBEX_TOKEN_KEEPER_URL }} | jq -r .access_token)" >> "${GITHUB_ENV}"
      - name: Build and Test
        run: script/ci
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ vars.PYPI_REPOSITORY_URL }}
          print-hash: true
